// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YourChickenGuide.Data;

#nullable disable

namespace YourChickenGuide.Migrations
{
    [DbContext(typeof(ApplicationDBContexts))]
    [Migration("20250904191034_NullableFieldsMore")]
    partial class NullableFieldsMore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("YourChickenGuide.Models.Chicken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Breed")
                        .HasColumnType("longtext");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("HatchDate")
                        .HasColumnType("date");

                    b.Property<string>("Legband_Id")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("Sex")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<int?>("father_Id")
                        .HasColumnType("int");

                    b.Property<int?>("mother_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("father_Id");

                    b.HasIndex("mother_Id");

                    b.ToTable("Chickens");
                });

            modelBuilder.Entity("YourChickenGuide.Models.Chicken", b =>
                {
                    b.HasOne("YourChickenGuide.Models.Chicken", null)
                        .WithMany()
                        .HasForeignKey("father_Id");

                    b.HasOne("YourChickenGuide.Models.Chicken", null)
                        .WithMany()
                        .HasForeignKey("mother_Id");
                });
#pragma warning restore 612, 618
        }
    }
}
