// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YourChickenGuide.Data;

#nullable disable

namespace YourChickenGuide.Migrations
{
    [DbContext(typeof(ApplicationDBContexts))]
    [Migration("20250620083426_AddFlocks")]
    partial class AddFlocks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("YourChickenGuide.Models.Chicken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Color")
                        .HasColumnType("longtext");

                    b.Property<int>("FlockManagerId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("HatchDate")
                        .HasColumnType("date");

                    b.Property<string>("Legband_Id")
                        .HasColumnType("longtext");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("Sex")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FlockManagerId");

                    b.ToTable("Chickens");
                });

            modelBuilder.Entity("YourChickenGuide.Models.FlockManager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FlockManagers");
                });

            modelBuilder.Entity("YourChickenGuide.Models.Chicken", b =>
                {
                    b.HasOne("YourChickenGuide.Models.FlockManager", "FlockManager")
                        .WithMany("Chickens")
                        .HasForeignKey("FlockManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlockManager");
                });

            modelBuilder.Entity("YourChickenGuide.Models.FlockManager", b =>
                {
                    b.Navigation("Chickens");
                });
#pragma warning restore 612, 618
        }
    }
}
